# Generated by Django 3.2.9 on 2021-11-15 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50)),
                ('book_isbn', models.CharField(max_length=17)),
                ('book_author', models.CharField(max_length=10)),
                ('book_publisher', models.CharField(max_length=50)),
                ('book_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('interview_times', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('reader_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('reader_name', models.CharField(max_length=50)),
                ('reader_sex', models.CharField(max_length=2)),
                ('reader_department', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'reader',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='books.book')),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField()),
                ('notes', models.CharField(max_length=50)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='books.reader')),
            ],
            options={
                'db_table': 'record',
                'unique_together': {('book', 'reader')},
            },
        ),
    ]
